---

meta_description: 'Ansible role to add the hashicorp repository for supported distributions.'

meta_galaxy_tags:
  - hashicorp
  - repository

meta_platforms:
  - { distribution: AlmaLinux, os_family: RedHat, tags: ['latest'] }
  - { distribution: Debian, os_family: Debian, tags: ['latest'] }
  - { distribution: Fedora, os_family: RedHat, tags: ['latest'] }
  - { distribution: Ubuntu, os_family: Debian, tags: ['latest'] }

meta_year_created: 2024

read_description: |-
  Add the hashicorp linux repository for supported distributions.

read_references:
  - "[Official Packaging Guide](https://www.hashicorp.com/official-packaging-guide)"

reqs_collections:
  - community.general
