---

meta_description: 'Ansible role for setting up apache httpd.'

meta_galaxy_tags:
  - apache
  - httpd
  - proxy
  - vhost
  - webserver

meta_platforms:
  - { distribution: Debian, os_family: Debian, tags: ['latest'] }
  - { distribution: Fedora, os_family: RedHat, tags: ['latest'] }

meta_year_created: 2024

read_description: |-
  Install apache httpd from os repositories and configure
    - default server
    - modules
    - reverse proxy
    - TLS
    - virtual hosts
  for version 2.4 or greater.

read_references:
  - "[Apache HTTP Server Documentation](https://httpd.apache.org/docs/)"
  - "[ArchWiki - Apache HTTP Server](https://wiki.archlinux.org/title/Apache_HTTP_Server)"
  - "[Fedora Quick Docs - Getting started with Apache HTTP Server](https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-apache-http-server/)"
