---
# name: ansible-roles
# file: inventory/host_vars/nexus_oss.yml

meta_description: 'Ansible role to set up Sonatype Nexus Repository OSS.'

meta_galaxy_tags:
  - nexus
  - repository

meta_platforms:
  - { distribution: AlmaLinux, os_family: RedHat, tags: ['latest'] }
  - { distribution: Debian, os_family: Debian, tags: ['latest'] }
  - { distribution: Fedora, os_family: RedHat, tags: ['latest'] }
  - { distribution: Ubuntu, os_family: Debian, tags: ['latest'] }

meta_year_created: 2024
