---
# name: ansible-roles
# file: inventory/host_vars/resolved.yml

meta_description: 'Ansible role for setting up systemd-resolved.'
meta_galaxy_tags:
  - systemd
  - resolved
meta_year_created: 2024

meta_platforms:
  - { distribution: AlmaLinux, os_family: RedHat, tags: ['latest'] }
  - { distribution: Archlinux, os_family: Archlinux, tags: ['latest'] }
  - { distribution: Debian, os_family: Debian, tags: ['latest'] }
  - { distribution: Fedora, os_family: RedHat, tags: ['latest'] }
  - { distribution: OpenSuse Leap, os_family: Suse, tags: ['latest'] }
  - { distribution: Ubuntu, os_family: Debian, tags: ['latest'] }

reqs_collections:
  - community.general
