---
# role: jomrr.samba-member
# file: inventory/host_vars/samba-member.yml

# default meta data
meta_year_created: "2021"

# default readme settings
read_description: |-
  This Ansible role installs and configures samba-member on supported platforms.

# Example playbooks
read_examples:
  - name: Simple example playbook
    description: |-
      A simple default example playbook for using jomrr.samba-member.
    code: |-
      ---
      # name: "jomrr.samba-member"
      # file: "playbook_samba-member.yml"

      - name: "PLAYBOOK | samba_member"
        hosts: "samba-member"
        gather_facts: true
        roles:
          - role: "jomrr.samba_member"

# references as single line in markdown
read_references: []
