---
# role: jomrr.sysctl
# file: inventory/host_vars/sysctl.yml

meta_description: 'Ansible role for configuring sysctl settings.'

meta_galaxy_tags:
  - kernel
  - procps
  - sysctl

meta_year_created: '2021'
