---
# role: jomrr.updates
# file: inventory/host_vars/updates.yml

# default meta data
meta_description: 'Ansible role for configuring automatic updates.'
meta_year_created: "2019"

# default readme settings
read_description: |-
  **Ansible role for configuring automatic updates.**

  The defaults of this role will install all available updates daily.

  On Debian-based systems it additionally will:

  - reboot at 04:00 a.m., if required and no users are logged in
  - autoremove unused kernel packages
  - autofix broken packages
  - Send mail to root, only on error

# Example playbooks
read_examples:
  - name: Simple example playbook
    description: |-
      A simple default example playbook for using jomrr.updates.
    code: |-
      ---
      # name: "jomrr.updates"
      # file: "playbook_updates.yml"

      - name: "PLAYBOOK | updates"
        hosts: "updates"
        gather_facts: true
        roles:
          - role: "jomrr.updates"

# references as single line in markdown
read_references: []
