---
# name: ansible-roles
# file: inventory/host_vars/virtinstall.yml

meta_description: 'Ansible role for deploying libvirt guests with virt-install.'

meta_galaxy_tags:
  - virtinstall
  - libvirt

meta_year_created: '2022'

read_description: |-
  Perform unattended install of libvirt guests with virt-install.

read_references:
  - "[man virt-install(1)](https://manpages.org/virt-install)"

reqs_collections:
  - name: community.libvirt
  - name: git+https://github.com/jomrr/ansible-collection-general
    version: main

mole_scenarios:
  - scenario:
      name: local
      create_sequence:
        - create
        - prepare
      check_sequence:
        - cleanup
        - destroy
        - create
        - prepare
        - converge
        - check
        - destroy
      converge_sequence:
        - dependency
        - create
        - prepare
        - converge
      destroy_sequence:
        - cleanup
        - destroy
      test_sequence:
        - dependency
        - lint
        - cleanup
        - destroy
        - create
        - prepare
        - converge
        - idempotence
        - verify
        - cleanup
        - destroy
    dependency:
      name: galaxy
      options:
        requirements-file: requirements.yml
    driver:
      name: default
      options:
        managed: false
        ansible_connection_options:
          ansible_connection: local
    lint: set -e; ansible-lint
    platforms:
      - name: localhost
        ansible_connection: local
    provisioner:
      name: ansible
      log: true
      playbooks:
        converge: ../resources/playbooks/converge.yml
        verify: ../resources/playbooks/verify.yml
    verifier:
      name: ansible

mole_playbooks:
  - name: resources/playbooks/converge.yml
    content: |-
      - name: "PLAYBOOK | Converge"
        hosts: all
        become: true
        gather_facts: true
        roles:
          - role: "{{ '{% raw %}{{' }} lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') {{ '}}{% endraw %}' }}"
  - name: resources/playbooks/verify.yml
    content: |-
      - name: "PLAYBOOK | Verify"
        hosts: all
        become: false
        gather_facts: false
        tasks:
          - name: "Check virt-install version"
            ansible.builtin.command:
              cmd: "virt-install --version"
            register: _virtinstall_version
            changed_when: false
          - name: "Check virt-install --version return code"
            ansible.builtin.assert:
              that: _virtinstall_version.rc == 0
