---
# name: ansible-roles
# file: inventory/host_vars/vm.yml

meta_description: 'Ansible role to manage libvirt guests.'

meta_galaxy_tags:
  - libvirt
  - virt
  - virtinstall
  - virtualization
  - vm

meta_year_created: 2024
