---
# name: ansible-roles
# file: inventory/group_vars/all/10-role-defaults.yml

# default role variables for all roles
role:
  author: Jonas Mauer
  allow_duplicate: false
  company: null
  description: "Ansible role for setting up {{ inventory_hostname }}."
  galaxy_tags: ['role', '{{ inventory_hostname }}']
  license: "MIT"
  min_ansible_version: "2.19"
  name: "{{ inventory_hostname }}"
  namespace: jomrr
  repo_prefix: ansible-role-
  scm_base_url: https://github.com
  year_created: "{{ lookup('pipe', 'git log --reverse --format=%ad --date=format:%Y | head -n1') | default(lookup('pipe', 'date +%Y')) }}"
