---
# name: ansible-roles
# file: inventory/group_vars/all/40-molecule-defaults.yml

# default molecule variables for all roles

molecule:
  defaults:
    dependency:
      name: galaxy
      requirements-file: meta/requirements.yml
    driver:
      name: podman
    lint: "ansible-lint"
    provisioner:
      name: ansible
      config_options:
        defaults:
          interpreter_python: auto_silent
          callback_whitelist: "profile_tasks, timer, yaml"
        ssh_connection:
          pipelining: true
      log: true
      playbooks:
        converge: ../resources/playbooks/converge.yml
        verify: ../resources/playbooks/verify.yml
    verifier:
      name: ansible
  enabled: true
  playbooks:
    - name: resources/playbooks/prepare.yml
      content: |-
        - name: "{{ role.name | upper }} | Prepare"
          hosts: all
          become: true
          gather_facts: true
          tasks:
            - name: "Ensure python3-libdnf5 is installed"
              ansible.builtin.raw: "dnf -qy install python3-libdnf5"
              changed_when: false
              when: ansible_pkg_mgr == "dnf5"

            - name: "Update apk cache"
              community.general.apk:
                update_cache: true
              when: ansible_pkg_mgr == "apk"

            - name: "Update apt cache"
              ansible.builtin.apt:
                update_cache: true
              when: ansible_pkg_mgr == "apt"

            - name: "Update dnf cache"
              ansible.builtin.dnf:
                update_cache: true
              when: ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "dnf5"

            - name: "Update pacman cache"
              community.general.pacman:
                update_cache: true
              when: ansible_pkg_mgr == "pacman"

            - name: "Update zypper cache"
              community.general.zypper:
                name: sudo
                update_cache: true
              when: ansible_pkg_mgr == "zypper"
    - name: resources/playbooks/converge.yml
      content: |-
        - name: "{{ role.name | upper }} | Converge"
          hosts: all
          gather_facts: true
          roles:
            - role: "{{ '{{' }} lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') {{ '}}' }}"
    - name: resources/playbooks/verify.yml
      content: |-
        - name: "{{ role.name | upper }} | Verify"
          hosts: all
          gather_facts: false
          tasks:
            - name: "Assert true"
              ansible.builtin.assert:
                that: "true"
                fail_msg: "This should never fail"
  scenarios:
    - scenario:
        name: default
      platforms:
        - name: "{{ role.name }}"
          image: "docker.io/${uns:-{{ role.namespace }}}/molecule-${img:-fedora}:${tag:-latest}"
          pre_build_image: true
          entrypoint: null
          command: null
          systemd: true
    - scenario:
        name: all
