---
# name: ansible-roles
# file: inventory/group_vars/all/60-pre-commit.yml

# default pre-commit hook versions for all roles
precommit:
  ansible_lint: v26.4.0
  commitizen: v4.13.10
  hooks: v6.0.0
  reuse: v6.2.0
