---
# name: ansible-roles
# file: inventory/group_vars/all/molecule_playbooks.yml

mole_playbooks:
  - name: resources/playbooks/prepare.yml
    content: |-
      - name: "{{ meta_role_name | upper }} | Prepare"
        hosts: all
        become: true
        gather_facts: true
        tasks:
          - name: "Update apk cache"
            community.general.apk:
              update_cache: true
            when: ansible_pkg_mgr == "apk"

          - name: "Update apt cache"
            ansible.builtin.apt:
              update_cache: true
            when: ansible_pkg_mgr == "apt"

          - name: "Update dnf cache"
            ansible.builtin.dnf:
              update_cache: true
            when: ansible_pkg_mgr == "dnf"

          - name: "Update pacman cache"
            community.general.pacman:
              update_cache: true
            when: ansible_pkg_mgr == "pacman"

          - name: "Update zypper cache"
            community.general.zypper:
              name: sudo
              update_cache: true
            when: ansible_pkg_mgr == "zypper"
  - name: resources/playbooks/converge.yml
    content: |-
      - name: "{{ meta_role_name | upper }} | Converge"
        hosts: all
        gather_facts: true
        roles:
          - role: "{{ '{% raw %}{{' }} lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') {{ '}}{% endraw %}' }}"
  - name: resources/playbooks/verify.yml
    content: |-
      - name: "{{ meta_role_name | upper }} | Verify"
        hosts: all
        gather_facts: false
        tasks:
          - name: "Assert true"
            ansible.builtin.assert:
              that: "true"
              fail_msg: "This should never fail"
