---
# name: ansible-roles
# file: playbooks/gitignore.yml

- name: "PLAYBOOK | Render .gitignore"
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Render .gitignore"
      ansible.builtin.template:
        src: ".gitignore.j2"
        dest: "{{ ansible_host }}/.gitignore"
        mode: "0644"
