---
# name: ansible-roles
# file: playbooks/license.yml

- name: "PLAYBOOK | License"
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Generate LICENSE file"
      ansible.builtin.template:
        src: 'LICENSE.j2'
        dest: "{{ ansible_host }}/LICENSE"
        mode: "0644"
