---
# name: ansible-roles
# file: playbooks/meta.yml

- name: "PLAYBOOK | Meta"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Create meta/requirements.yml"
      when: reqs_roles | length > 0
      block:
        - name: "Ensure meta/ exists"
          ansible.builtin.file:
            path: "{{ ansible_host }}/meta"
            state: directory
            mode: "0755"
        - name: "Generate meta/requirements.yml"
          ansible.builtin.template:
            src: "meta/requirements.yml.j2"
            dest: "{{ ansible_host }}/meta/requirements.yml"
            mode: "0644"
            validate: "ansible-lint %s"
    - name: "Generate requirements.yml"
      ansible.builtin.template:
        src: "meta/requirements.yml.j2"
        dest: "{{ ansible_host }}/meta/requirements.yml"
        mode: "0644"
        validate: "ansible-lint %s"
      when: reqs_collections | length > 0
        or reqs_roles | length > 0
    - name: "Remove meta/requirements.yml when no role dependencies"
      ansible.builtin.file:
        path: "{{ ansible_host }}/meta/requirements.yml"
        state: absent
      when: reqs_roles | length = 0
    - name: "Remove requirements.yml when no dependencies"
      ansible.builtin.file:
        path: "{{ ansible_host }}/requirements.yml"
        state: absent
      when: reqs_collections | length = 0
        and reqs_roles | length = 0
