---
# name: ansible-roles
# file: playbooks/meta.yml

- name: "PLAYBOOK | Meta"
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Ensure meta directory exists"
      ansible.builtin.file:
        path: "{{ ansible_host }}/meta"
        state: directory
        mode: "0755"

    - name: "Render meta/main.yml"
      ansible.builtin.template:
        src: "meta/main.yml.j2"
        dest: "{{ ansible_host }}/meta/main.yml"
        mode: "0644"
        validate: "ansible-lint %s"

    - name: "Render meta/argument_specs.yml"
      ansible.builtin.template:
        src: "meta/argument_specs.yml.j2"
        dest: "{{ ansible_host }}/meta/argument_specs.yml"
        mode: "0644"
        validate: "ansible-lint %s"
      when: argument_specs is defined

    - name: "Remove meta/argument_specs.yml"
      ansible.builtin.file:
        path: "{{ ansible_host }}/meta/argument_specs.yml"
        state: absent
      when: argument_specs is not defined
