---
# name: ansible-roles
# file: playbooks/molecule.yml

- name: "PLAYBOOK | Molecule scenarios"
  hosts: "{{ target | default('all') }}"
  gather_facts: true
  tasks:
    - name: "Render molecule resources and scenarios"
      when: molecule.enabled | bool
      block:
        - name: "Ensure molecule resource directories exist"
          ansible.builtin.file:
            path: "{{ ansible_host }}/molecule/{{ item.name | dirname }}"
            state: directory
            mode: "0755"
          loop: "{{ molecule.playbooks }}"

        - name: "Render molecule resources"
          ansible.builtin.template:
            src: "molecule/playbook.yml.j2"
            dest: "{{ ansible_host }}/molecule/{{ item.name }}"
            mode: "0644"
            validate: "ansible-lint %s"
          loop: "{{ molecule.playbooks }}"

        - name: "Ensure molecule scenario directories exist"
          ansible.builtin.file:
            path: "{{ ansible_host }}/molecule/{{ item.scenario.name }}"
            state: directory
            mode: "0755"
          loop: "{{ molecule.scenarios }}"

        - name: "Render molecule scenarios"
          ansible.builtin.template:
            src: "molecule/molecule.yml.j2"
            dest: "{{ ansible_host }}/molecule/{{ item.scenario.name }}/molecule.yml"
            mode: "0644"
            validate: "ansible-lint %s"
          loop: "{{ molecule.scenarios }}"
