---
# name: ansible-roles
# file: playbooks/pyproject.yml

- name: "PLAYBOOK | Render pyproject"
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Render pyproject.toml"
      ansible.builtin.template:
        src: "pyproject.toml.j2"
        dest: "{{ ansible_host }}/pyproject.toml"
        mode: "0644"
