---
# name: ansible-roles
# file: playbooks/pyproject.yml

- name: "PLAYBOOK | Pyproject"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Set fact 'meta_release_version'"
      ansible.builtin.set_fact:
        meta_release_version: "{{ lookup('jomrr.dev.github_version', \
          lookup('ansible.builtin.env', 'GH_TOKEN'), meta_namespace, meta_repo_name) }}"
    - name: "Generate pyproject.toml"
      ansible.builtin.template:
        src: 'pyproject.toml.j2'
        dest: "{{ ansible_host }}/pyproject.toml"
        mode: "0644"
