---
# name: ansible-roles
# file: playbooks/requirements-python.yml

- name: "PLAYBOOK | Manage Python requirements"
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  vars:
    has_python_requirements: "{{ requirements.pip | default([]) | length > 0 }}"
  tasks:
    - name: "Render requirements.txt"
      ansible.builtin.template:
        src: "requirements.txt.j2"
        dest: "{{ ansible_host }}/requirements.txt"
        mode: "0644"
      when: has_python_requirements | bool

    - name: "Remove empty requirements.txt"
      ansible.builtin.file:
        path: "{{ ansible_host }}/requirements.txt"
        state: absent
      when: not has_python_requirements | bool
